// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-6kiWdM8jzV5zZYCIsmGuAUs1dzOagA',
    appId: '1:535371314165:web:05851e5f7d56557bfce6bc',
    messagingSenderId: '535371314165',
    projectId: 'saferide-3d54f',
    authDomain: 'saferide-3d54f.firebaseapp.com',
    storageBucket: 'saferide-3d54f.firebasestorage.app',
    measurementId: 'G-SVZJ16VBGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq4atg1o9-H5Vypf9dam4whPpS3tXfpHA',
    appId: '1:104194667851:android:975cac453fa8ffea3ba4ce',
    messagingSenderId: '104194667851',
    projectId: 'saferide1-9bf21',
    storageBucket: 'saferide1-9bf21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXWn5JMDsRzgLStE_-jQ2_GnA4EvcvgI0',
    appId: '1:535371314165:ios:45b09f74dc218980fce6bc',
    messagingSenderId: '535371314165',
    projectId: 'saferide-3d54f',
    storageBucket: 'saferide-3d54f.firebasestorage.app',
    iosBundleId: 'com.example.saferideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXWn5JMDsRzgLStE_-jQ2_GnA4EvcvgI0',
    appId: '1:535371314165:ios:45b09f74dc218980fce6bc',
    messagingSenderId: '535371314165',
    projectId: 'saferide-3d54f',
    storageBucket: 'saferide-3d54f.firebasestorage.app',
    iosBundleId: 'com.example.saferideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD-6kiWdM8jzV5zZYCIsmGuAUs1dzOagA',
    appId: '1:535371314165:web:ba49417102455fd2fce6bc',
    messagingSenderId: '535371314165',
    projectId: 'saferide-3d54f',
    authDomain: 'saferide-3d54f.firebaseapp.com',
    storageBucket: 'saferide-3d54f.firebasestorage.app',
    measurementId: 'G-WB2D7WBW1S',
  );
}